export { authService } from './auth';
export { departmentService } from './department';
export { employeeService } from './employee';
export { attendanceService } from './attendance';
export { leaveService } from './leave';
export { taskService } from './task';
export { payrollService } from './payroll';
export { recruitmentService } from './recruitment';
export { documentService } from './document';
export { chatService } from './chat';
export { reportService } from './report';
export { searchService } from './search';
export { settingsService } from './settings';
export { uploadService } from './upload';
export { tenantService } from './tenant';
export { mobileConfigService } from './mobileConfig';
export { holidayService } from './holiday';
// Re-export existing separate services
export { supportService } from './supportService';
export { shiftService } from './shiftService';
export { default as performanceService } from './performanceService';
export { default as assetService } from './assetService';
export { default as auditService } from './auditService';
export { paymentService } from './payment';
