import React, { useEffect, useState } from 'react';
import { payrollService, employeeService } from '../services';
import { useSettings } from '../hooks/useSettings.jsx';
import {
  FaMoneyBillWave,
  FaRobot,
  FaPlus,
  FaFilter,
  FaSearch,
  FaTimes,
  FaFileInvoiceDollar,
  FaCheckCircle,
  FaTimesCircle,
  FaHourglassHalf,
  FaEdit,
  FaTrash,
  FaPlay
} from 'react-icons/fa';

const Payroll = () => {
  const { getSetting, getSettingNumber, getSettingBoolean } = useSettings();
  const [payrollRecords, setPayrollRecords] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [payrollStatistics, setPayrollStatistics] = useState({
    total_records: 0,
    pending_records: 0,
    paid_records: 0,
    cancelled_records: 0,
    total_pending_amount: 0,
    total_paid_amount: 0,
    total_cancelled_amount: 0,
    total_amount: 0
  });
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [showAutoGenerateModal, setShowAutoGenerateModal] = useState(false);
  const [editingPayroll, setEditingPayroll] = useState(null);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [autoGenerateLoading, setAutoGenerateLoading] = useState(false);
  const [filters, setFilters] = useState({
    employee_id: '',
    month: '',
    year: new Date().getFullYear(),
    payment_status: ''
  });
  const [formData, setFormData] = useState({
    employee_id: '',
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
    basic_salary: '',
    allowances: 0,
    deductions: 0,
    overtime_pay: 0,
    bonus: 0,
    tax: 0,
    payment_method: 'bank_transfer',
    notes: ''
  });
  const [autoGenerateData, setAutoGenerateData] = useState({
    employee_id: '',
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear()
  });
  const [pagination, setPagination] = useState({
    currentPage: 1,
    totalPages: 1,
    totalItems: 0,
    itemsPerPage: 10,
    hasNext: false,
    hasPrev: false
  });

  useEffect(() => {
    loadPayroll();
    loadEmployees();
    fetchPayrollStatistics();
  }, []);

  const fetchPayrollStatistics = async () => {
    try {
      const response = await payrollService.getStatistics(filters);
      setPayrollStatistics(response.data);
    } catch (error) {
      console.error('Failed to fetch payroll statistics:', error);
    }
  };

  const loadPayroll = async (page = 1) => {
    try {
      setLoading(true);
      const params = {
        page: page,
        limit: 10,
        ...filters
      };

      const response = await payrollService.getAll(params);
      setPayrollRecords(response.data);
      setPagination(response.pagination);
      setError('');
    } catch (error) {
      setError('Failed to load payroll: ' + (error.response?.data?.message || error.message));
    } finally {
      setLoading(false);
    }
  };

  const loadEmployees = async () => {
    try {
      const response = await employeeService.getAll();
      setEmployees(response.data);
    } catch (error) {
      console.error('Failed to load employees:', error);
    }
  };

  const handlePageChange = (newPage) => {
    if (newPage >= 1 && newPage <= pagination.totalPages) {
      loadPayroll(newPage);
    }
  };

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    setFilters(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const applyFilters = () => {
    loadPayroll(1);
    fetchPayrollStatistics();
  };

  const clearFilters = () => {
    setFilters({
      employee_id: '',
      month: '',
      year: new Date().getFullYear(),
      payment_status: ''
    });
    loadPayroll(1);
    fetchPayrollStatistics();
  };

  const calculateNetSalary = () => {
    const basic = parseFloat(formData.basic_salary) || 0;
    const allowances = parseFloat(formData.allowances) || 0;
    const overtime = parseFloat(formData.overtime_pay) || 0;
    const bonus = parseFloat(formData.bonus) || 0;
    const deductions = parseFloat(formData.deductions) || 0;
    const tax = parseFloat(formData.tax) || 0;
    return (basic + allowances + overtime + bonus - deductions - tax).toFixed(2);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    try {
      if (editingPayroll) {
        await payrollService.update(editingPayroll.payroll_id, formData);
        setSuccess('Payroll updated successfully!');
      } else {
        await payrollService.create(formData);
        setSuccess('Payroll record created successfully!');
      }
      loadPayroll();
      handleCloseModal();
      setTimeout(() => setSuccess(''), 3000);
    } catch (error) {
      setError('Operation failed: ' + (error.response?.data?.message || error.message));
    }
  };

  const handleAutoGenerate = async (e) => {
    e.preventDefault();
    setError('');
    setAutoGenerateLoading(true);

    try {
      const response = await payrollService.generateAutomatic(autoGenerateData);
      setSuccess('Payroll generated successfully!');
      loadPayroll();
      handleCloseAutoGenerateModal();
      setTimeout(() => setSuccess(''), 3000);
    } catch (error) {
      setError('Auto generation failed: ' + (error.response?.data?.message || error.message));
    } finally {
      setAutoGenerateLoading(false);
    }
  };

  const handleBulkGenerate = async () => {
    if (window.confirm('Generate payroll for all employees for the selected month and year?')) {
      setError('');
      setAutoGenerateLoading(true);

      try {
        const response = await payrollService.generateBulk({
          month: autoGenerateData.month,
          year: autoGenerateData.year
        });
        setSuccess(response.message);
        loadPayroll();
        setTimeout(() => setSuccess(''), 3000);
      } catch (error) {
        setError('Bulk generation failed: ' + (error.response?.data?.message || error.message));
      } finally {
        setAutoGenerateLoading(false);
      }
    }
  };

  const handleProcessPayment = async (id) => {
    if (window.confirm('Process this payment? This will mark it as paid.')) {
      try {
        await payrollService.processPayment(id, 'bank_transfer');
        setSuccess('Payment processed successfully!');
        loadPayroll();
        setTimeout(() => setSuccess(''), 3000);
      } catch (error) {
        setError('Process payment failed: ' + (error.response?.data?.message || error.message));
      }
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this payroll record?')) {
      try {
        await payrollService.delete(id);
        setSuccess('Payroll record deleted!');
        loadPayroll();
        setTimeout(() => setSuccess(''), 3000);
      } catch (error) {
        setError('Delete failed: ' + (error.response?.data?.message || error.message));
      }
    }
  };

  const handleEdit = (payroll) => {
    setEditingPayroll(payroll);
    setFormData({
      employee_id: payroll.employee_id,
      month: payroll.month,
      year: payroll.year,
      basic_salary: payroll.basic_salary,
      allowances: payroll.allowances || 0,
      deductions: payroll.deductions || 0,
      overtime_pay: payroll.overtime_pay || 0,
      bonus: payroll.bonus || 0,
      tax: payroll.tax || 0,
      payment_method: payroll.payment_method || 'bank_transfer',
      notes: payroll.notes || ''
    });
    setShowModal(true);
  };

  const handleOpenAutoGenerateModal = () => {
    setShowAutoGenerateModal(true);
  };

  const handleCloseAutoGenerateModal = () => {
    setShowAutoGenerateModal(false);
    setAutoGenerateData({
      employee_id: '',
      month: new Date().getMonth() + 1,
      year: new Date().getFullYear()
    });
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingPayroll(null);
    setError('');
    setFormData({
      employee_id: '',
      month: new Date().getMonth() + 1,
      year: new Date().getFullYear(),
      basic_salary: '',
      allowances: 0,
      deductions: 0,
      overtime_pay: 0,
      bonus: 0,
      tax: 0,
      payment_method: 'bank_transfer',
      notes: ''
    });
  };

  if (loading) return <div className="loading">Loading...</div>;

  const currencySymbol = getSetting('currency_symbol', '$');
  const statusColors = {
    pending: 'warning',
    paid: 'success',
    cancelled: 'danger'
  };

  return (
    <div className="container" style={{ paddingBottom: '2rem' }}>
      {/* Page Header */}
      <div className="page-header" style={{ marginTop: '1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 className="page-title">Payroll Management</h1>
          <p className="page-description">Manage employee salaries, payments, and payroll records.</p>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button className="btn btn-primary" onClick={handleOpenAutoGenerateModal}>
            <FaRobot /> Auto Generate
          </button>
          <button className="btn btn-primary" onClick={() => setShowModal(true)}>
            <FaPlus /> New Record
          </button>
        </div>
      </div>

      {error && <div className="alert alert-error">{error}</div>}
      {success && <div className="alert alert-success">{success}</div>}

      {/* Statistics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6" style={{ marginBottom: '2rem' }}>
        <div className="stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div style={{ background: '#e0e7ff', padding: '0.75rem', borderRadius: '0.5rem', color: '#4f46e5' }}>
              <FaHourglassHalf size={20} />
            </div>
            <span style={{ fontSize: '0.75rem', fontWeight: 'bold', textTransform: 'uppercase', color: '#9ca3af' }}>Pending</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '0.5rem' }}>
            <h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827', lineHeight: 1 }}>{currencySymbol}{parseFloat(payrollStatistics.total_pending_amount).toFixed(2)}</h3>
          </div>
          <span style={{ fontSize: '0.875rem', color: '#6b7280' }}>{payrollStatistics.pending_records} records</span>
        </div>
        <div className="stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div style={{ background: '#d1fae5', padding: '0.75rem', borderRadius: '0.5rem', color: '#059669' }}>
              <FaCheckCircle size={20} />
            </div>
            <span style={{ fontSize: '0.75rem', fontWeight: 'bold', textTransform: 'uppercase', color: '#9ca3af' }}>Paid</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '0.5rem' }}>
            <h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827', lineHeight: 1 }}>{currencySymbol}{parseFloat(payrollStatistics.total_paid_amount).toFixed(2)}</h3>
          </div>
          <span style={{ fontSize: '0.875rem', color: '#6b7280' }}>{payrollStatistics.paid_records} records</span>
        </div>
        <div className="stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div style={{ background: '#fee2e2', padding: '0.75rem', borderRadius: '0.5rem', color: '#dc2626' }}>
              <FaTimesCircle size={20} />
            </div>
            <span style={{ fontSize: '0.75rem', fontWeight: 'bold', textTransform: 'uppercase', color: '#9ca3af' }}>Cancelled</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '0.5rem' }}>
            <h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827', lineHeight: 1 }}>{currencySymbol}{parseFloat(payrollStatistics.total_cancelled_amount).toFixed(2)}</h3>
          </div>
          <span style={{ fontSize: '0.875rem', color: '#6b7280' }}>{payrollStatistics.cancelled_records} records</span>
        </div>
        <div className="stat-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <div style={{ background: '#f3f4f6', padding: '0.75rem', borderRadius: '0.5rem', color: '#4b5563' }}>
              <FaMoneyBillWave size={20} />
            </div>
            <span style={{ fontSize: '0.75rem', fontWeight: 'bold', textTransform: 'uppercase', color: '#9ca3af' }}>Total</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '0.5rem' }}>
            <h3 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827', lineHeight: 1 }}>{currencySymbol}{parseFloat(payrollStatistics.total_amount).toFixed(2)}</h3>
          </div>
          <span style={{ fontSize: '0.875rem', color: '#6b7280' }}>{payrollStatistics.total_records} records</span>
        </div>
      </div>

      {/* Filter Section */}
      <div className="card" style={{ marginBottom: '2rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem', borderBottom: '1px solid #e5e7eb', paddingBottom: '0.75rem' }}>
          <FaFilter className="text-gray-400" />
          <h3 style={{ fontSize: '1rem', fontWeight: '600', color: '#374151', margin: 0 }}>Filter Records</h3>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4" style={{ marginBottom: '1rem' }}>
          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Employee</label>
            <select
              className="form-input"
              name="employee_id"
              value={filters.employee_id}
              onChange={handleFilterChange}
            >
              <option value="">All Employees</option>
              {employees.map(emp => (
                <option key={emp.employee_id} value={emp.employee_id}>
                  {emp.first_name} {emp.last_name}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Month</label>
            <select
              className="form-input"
              name="month"
              value={filters.month}
              onChange={handleFilterChange}
            >
              <option value="">All Months</option>
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(m => (
                <option key={m} value={m}>
                  {new Date(2020, m - 1, 1).toLocaleString('default', { month: 'long' })}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Year</label>
            <input
              type="number"
              className="form-input"
              name="year"
              value={filters.year}
              onChange={handleFilterChange}
              min="2020"
              max="2030"
            />
          </div>

          <div className="form-group" style={{ marginBottom: 0 }}>
            <label className="form-label">Status</label>
            <select
              className="form-input"
              name="payment_status"
              value={filters.payment_status}
              onChange={handleFilterChange}
            >
              <option value="">All Statuses</option>
              <option value="pending">Pending</option>
              <option value="paid">Paid</option>
              <option value="cancelled">Cancelled</option>
            </select>
          </div>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end' }}>
          <button className="btn btn-secondary" onClick={clearFilters}>
            <FaTimes /> Clear
          </button>
          <button className="btn btn-primary" onClick={applyFilters}>
            <FaSearch /> Apply Filters
          </button>
        </div>
      </div>

      <div className="card" style={{ padding: 0, overflowX: 'auto' }}>
        <table className="table">
          <thead>
            <tr>
              <th>Employee</th>
              <th>Period</th>
              <th>Basic Salary</th>
              <th>Allowances</th>
              <th>Deductions</th>
              <th>Net Salary</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {payrollRecords.length === 0 ? (
              <tr>
                <td colSpan="8" style={{ textAlign: 'center', padding: '3rem', color: '#6b7280' }}>
                  <div className="empty-state">
                    <div className="empty-state-icon">
                      <FaFileInvoiceDollar />
                    </div>
                    <h3 className="empty-state-title">No payroll records found</h3>
                    <p className="empty-state-description">Adjust filters or create a new record.</p>
                  </div>
                </td>
              </tr>
            ) : (
              payrollRecords.map((record) => (
                <tr key={record.payroll_id}>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center' }}>
                      <div style={{ height: '2rem', width: '2rem', borderRadius: '50%', background: '#e0e7ff', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#4f46e5', fontWeight: 'bold', fontSize: '0.75rem', marginRight: '0.75rem' }}>
                        {record.employee_name.charAt(0)}
                      </div>
                      <div style={{ fontWeight: '500', color: '#111827' }}>{record.employee_name}</div>
                    </div>
                  </td>
                  <td>{new Date(2020, record.month - 1, 1).toLocaleString('default', { month: 'short' })} {record.year}</td>
                  <td>{currencySymbol}{parseFloat(record.basic_salary || 0).toFixed(2)}</td>
                  <td>{currencySymbol}{(parseFloat(record.allowances || 0) + parseFloat(record.overtime_pay || 0) + parseFloat(record.bonus || 0)).toFixed(2)}</td>
                  <td>{currencySymbol}{(parseFloat(record.deductions || 0) + parseFloat(record.tax || 0)).toFixed(2)}</td>
                  <td><strong>{currencySymbol}{parseFloat(record.net_salary || 0).toFixed(2)}</strong></td>
                  <td>
                    <span className={`badge badge-${statusColors[record.payment_status]}`}>
                      {record.payment_status === 'paid' && <FaCheckCircle size={10} style={{ marginRight: '4px' }} />}
                      {record.payment_status === 'pending' && <FaHourglassHalf size={10} style={{ marginRight: '4px' }} />}
                      {record.payment_status === 'cancelled' && <FaTimesCircle size={10} style={{ marginRight: '4px' }} />}
                      {record.payment_status.charAt(0).toUpperCase() + record.payment_status.slice(1)}
                    </span>
                  </td>
                  <td>
                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                      {record.payment_status === 'pending' && (
                        <button className="btn btn-success" style={{ padding: '0.25rem 0.5rem', fontSize: '0.75rem' }} onClick={() => handleProcessPayment(record.payroll_id)} title="Process Payment">
                          <FaPlay />
                        </button>
                      )}
                      <button className="btn btn-secondary" style={{ padding: '0.25rem 0.5rem', fontSize: '0.75rem' }} onClick={() => handleEdit(record)} title="Edit">
                        <FaEdit />
                      </button>
                      <button className="btn btn-danger" style={{ padding: '0.25rem 0.5rem', fontSize: '0.75rem' }} onClick={() => handleDelete(record.payroll_id)} title="Delete">
                        <FaTrash />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination Controls */}
      {pagination.totalPages > 1 && (
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', marginTop: '2rem', gap: '0.5rem' }}>
          <button
            className="btn btn-secondary"
            onClick={() => handlePageChange(pagination.currentPage - 1)}
            disabled={!pagination.hasPrev}
          >
            Previous
          </button>

          {/* Numbered page buttons */}
          {Array.from({ length: Math.min(5, pagination.totalPages) }, (_, i) => {
            let pageNum;
            if (pagination.totalPages <= 5) {
              pageNum = i + 1;
            } else if (pagination.currentPage <= 3) {
              pageNum = i + 1;
            } else if (pagination.currentPage >= pagination.totalPages - 2) {
              pageNum = pagination.totalPages - 4 + i;
            } else {
              pageNum = pagination.currentPage - 2 + i;
            }

            return (
              <button
                key={pageNum}
                className={`btn ${pageNum === pagination.currentPage ? 'btn-primary' : 'btn-secondary'}`}
                onClick={() => handlePageChange(pageNum)}
                style={{ minWidth: '40px' }}
              >
                {pageNum}
              </button>
            );
          })}

          <button
            className="btn btn-secondary"
            onClick={() => handlePageChange(pagination.currentPage + 1)}
            disabled={!pagination.hasNext}
          >
            Next
          </button>

          <span style={{ marginLeft: '1rem', color: '#6b7280' }}>
            Page {pagination.currentPage} of {pagination.totalPages}
            {' '}({pagination.totalItems} total records)
          </span>
        </div>
      )}

      {/* Add/Edit Payroll Modal */}
      {showModal && (
        <div className="modal-overlay" onClick={handleCloseModal}>
          <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '700px', width: '100%' }}>
            <div style={{ marginBottom: '1.5rem', borderBottom: '1px solid #e5e7eb', paddingBottom: '1rem' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827' }}>{editingPayroll ? 'Edit Payroll Record' : 'New Payroll Record'}</h2>
              <p style={{ color: '#6b7280', fontSize: '0.875rem' }}>Enter payroll details for the employee.</p>
            </div>

            {error && <div className="alert alert-error" style={{ marginBottom: '1rem' }}>{error}</div>}

            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label className="form-label">Employee *</label>
                <select className="form-input" value={formData.employee_id} onChange={(e) => setFormData({ ...formData, employee_id: e.target.value })} required>
                  <option value="">Select Employee</option>
                  {employees.map(emp => <option key={emp.employee_id} value={emp.employee_id}>{emp.first_name} {emp.last_name}</option>)}
                </select>
              </div>

              <div className="grid grid-cols-2" style={{ gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Month *</label>
                  <select className="form-input" value={formData.month} onChange={(e) => setFormData({ ...formData, month: parseInt(e.target.value) })} required>
                    {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(m => <option key={m} value={m}>{new Date(2020, m - 1, 1).toLocaleString('default', { month: 'long' })}</option>)}
                  </select>
                </div>

                <div className="form-group">
                  <label className="form-label">Year *</label>
                  <input type="number" className="form-input" value={formData.year} onChange={(e) => setFormData({ ...formData, year: parseInt(e.target.value) })} min="2020" max="2030" required />
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Basic Salary *</label>
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                  <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.basic_salary} onChange={(e) => setFormData({ ...formData, basic_salary: e.target.value })} step="0.01" required />
                </div>
              </div>

              <div className="grid grid-cols-2" style={{ gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Allowances</label>
                  <div style={{ position: 'relative' }}>
                    <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                    <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.allowances} onChange={(e) => setFormData({ ...formData, allowances: e.target.value })} step="0.01" />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Deductions</label>
                  <div style={{ position: 'relative' }}>
                    <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                    <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.deductions} onChange={(e) => setFormData({ ...formData, deductions: e.target.value })} step="0.01" />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Overtime Pay</label>
                  <div style={{ position: 'relative' }}>
                    <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                    <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.overtime_pay} onChange={(e) => setFormData({ ...formData, overtime_pay: e.target.value })} step="0.01" />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Bonus</label>
                  <div style={{ position: 'relative' }}>
                    <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                    <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.bonus} onChange={(e) => setFormData({ ...formData, bonus: e.target.value })} step="0.01" />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Tax</label>
                  <div style={{ position: 'relative' }}>
                    <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: '#6b7280' }}>{currencySymbol}</span>
                    <input type="number" className="form-input" style={{ paddingLeft: '25px' }} value={formData.tax} onChange={(e) => setFormData({ ...formData, tax: e.target.value })} step="0.01" />
                  </div>
                </div>
              </div>

              <div className="form-group" style={{ background: '#f3f4f6', padding: '1rem', borderRadius: '0.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <label className="form-label" style={{ margin: 0 }}>Net Salary:</label>
                <strong style={{ fontSize: '1.25rem', color: '#4f46e5' }}>{currencySymbol}{calculateNetSalary()}</strong>
              </div>

              <div className="form-group">
                <label className="form-label">Payment Method</label>
                <select className="form-input" value={formData.payment_method} onChange={(e) => setFormData({ ...formData, payment_method: e.target.value })}>
                  <option value="bank_transfer">Bank Transfer</option>
                  <option value="cash">Cash</option>
                  <option value="check">Check</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Notes</label>
                <textarea className="form-input" value={formData.notes} onChange={(e) => setFormData({ ...formData, notes: e.target.value })} rows="3" placeholder="Additional notes..." />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem', marginTop: '2rem', paddingTop: '1rem', borderTop: '1px solid #e5e7eb' }}>
                <button type="button" className="btn btn-secondary" onClick={handleCloseModal}>Cancel</button>
                <button type="submit" className="btn btn-primary">{editingPayroll ? 'Update Record' : 'Create Record'}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Auto Generate Modal */}
      {showAutoGenerateModal && (
        <div className="modal-overlay" onClick={handleCloseAutoGenerateModal}>
          <div className="modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: '500px', width: '100%' }}>
            <div style={{ marginBottom: '1.5rem', borderBottom: '1px solid #e5e7eb', paddingBottom: '1rem' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#111827' }}>Auto Generate Payroll</h2>
              <p style={{ color: '#6b7280', fontSize: '0.875rem' }}>Automatically calculate payroll based on employee salary settings.</p>
            </div>

            {error && <div className="alert alert-error" style={{ marginBottom: '1rem' }}>{error}</div>}

            <form onSubmit={handleAutoGenerate}>
              <div className="form-group">
                <label className="form-label">Employee</label>
                <select className="form-input" value={autoGenerateData.employee_id} onChange={(e) => setAutoGenerateData({ ...autoGenerateData, employee_id: e.target.value })}>
                  <option value="">All Employees</option>
                  {employees.map(emp => <option key={emp.employee_id} value={emp.employee_id}>{emp.first_name} {emp.last_name}</option>)}
                </select>
              </div>

              <div className="grid grid-cols-2" style={{ gap: '1rem' }}>
                <div className="form-group">
                  <label className="form-label">Month *</label>
                  <select className="form-input" value={autoGenerateData.month} onChange={(e) => setAutoGenerateData({ ...autoGenerateData, month: parseInt(e.target.value) })} required>
                    {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(m => <option key={m} value={m}>{new Date(2020, m - 1, 1).toLocaleString('default', { month: 'long' })}</option>)}
                  </select>
                </div>

                <div className="form-group">
                  <label className="form-label">Year *</label>
                  <input type="number" className="form-input" value={autoGenerateData.year} onChange={(e) => setAutoGenerateData({ ...autoGenerateData, year: parseInt(e.target.value) })} min="2020" max="2030" required />
                </div>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '1.5rem' }}>
                <button type="submit" className="btn btn-primary" disabled={autoGenerateLoading} style={{ width: '100%' }}>
                  {autoGenerateLoading ? 'Generating...' : 'Generate for Selected Employee(s)'}
                </button>
                <button type="button" className="btn btn-outline" onClick={handleBulkGenerate} disabled={autoGenerateLoading} style={{ width: '100%' }}>
                  {autoGenerateLoading ? 'Generating...' : 'Generate for All Employees'}
                </button>
                <button type="button" className="btn btn-secondary" onClick={handleCloseAutoGenerateModal} disabled={autoGenerateLoading} style={{ width: '100%' }}>
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Payroll;