const comparisonData = {
  bamboohr: {
    name: 'BambooHR',
    slug: 'bamboohr',
    headline: 'HRMS Pro vs BambooHR',
    title: 'HRMS Pro vs BambooHR Comparison | Modern AI-Powered HR',
    description: 'Compare HRMS Pro vs BambooHR. See why thousands of teams are switching to HRMS Pro for AI-powered HR, global payroll, and modern workforce analytics.',
    subheadline: 'BambooHR is a solid choice for basic HR. But modern teams need more — AI-powered insights, global payroll, and real-time analytics.',
    advantages: [
      { title: 'AI-powered automation', desc: 'HRMS Pro automates approvals, flags compliance risks, and predicts attrition. BambooHR has no AI layer.', icon: '🤖' },
      { title: 'Global payroll built in', desc: 'Multi-currency payroll across 150+ countries with auto tax compliance. BambooHR requires expensive third-party payroll add-ons.', icon: '🌍' },
      { title: 'Dynamic settings integration', desc: 'Currency, tax rates, and working hours update instantly across Payroll and Attendance. BambooHR requires manual configuration.', icon: '⚙️' },
      { title: '150+ pre-built metrics', desc: 'Real-time dashboards and custom reports vs BambooHR\'s basic historical reporting.', icon: '📊' },
      { title: 'Mobile-first everywhere', desc: 'Native iOS/Android apps for attendance, leaves, payslips, and self-service — not a watered-down web view.', icon: '📱' },
      { title: 'Better value', desc: 'All features included at $6/employee/month. BambooHR charges extra for payroll, reporting, and support.', icon: '💰' },
    ],
    features: [
      ['Core HR Database', true, true],
      ['AI-Powered Insights', true, false],
      ['Global Payroll (150+ countries)', true, false],
      ['Dynamic Currency Settings', true, false],
      ['Auto Tax Calculation', true, false],
      ['Performance Reviews', true, true],
      ['Recruitment ATS', true, true],
      ['Onboarding Workflows', true, true],
      ['Mobile App', true, true],
      ['Biometric Attendance', true, false],
      ['Geo-fencing', true, false],
      ['Custom Reporting', true, false],
      ['Slack / Teams Integration', true, true],
      ['API Access', true, true],
      ['Dedicated Support', true, false],
      ['Multi-Country Compliance', true, false],
    ],
    pricingUs: '$6 /employee /month',
    pricingThem: '$10+ /employee /month + payroll add-on',
    verdict: 'BambooHR is reliable for basic HR, but HRMS Pro delivers AI-powered automation, global payroll, and advanced analytics — all at a lower price.'
  },

  gusto: {
    name: 'Gusto',
    slug: 'gusto',
    headline: 'HRMS Pro vs Gusto',
    title: 'HRMS Pro vs Gusto Comparison | Enterprise-Ready HR Platform',
    description: 'Compare HRMS Pro vs Gusto. See how HRMS Pro scales beyond payroll with AI, performance management, and global workforce tools.',
    subheadline: 'Gusto is great for simple payroll. But growing companies quickly outgrow it. HRMS Pro scales from 10 to 10,000+ employees.',
    advantages: [
      { title: 'Scales with you', desc: 'Gusto caps out at ~100 employees for full features. HRMS Pro is built for companies of any size.', icon: '📈' },
      { title: 'Global workforce support', desc: 'Multi-country payroll and compliance vs Gusto (US-only). HRMS Pro supports 150+ countries.', icon: '🌐' },
      { title: 'Performance management', desc: 'OKR tracking, 360 reviews, and continuous feedback — Gusto has none of this.', icon: '🎯' },
      { title: 'AI-driven insights', desc: 'Predict attrition, identify skill gaps, and automate workflows with AI. Gusto offers basic reports only.', icon: '🔮' },
      { title: 'Integrated payroll & HR', desc: 'Full recruitment and onboarding in one platform. Gusto requires separate tools.', icon: '🔗' },
      { title: 'Smart overtime detection', desc: 'Configurable working hours with automatic overtime calculation. Gusto lacks advanced attendance features.', icon: '⏰' },
    ],
    features: [
      ['Payroll Processing', true, true],
      ['Multi-Country Payroll', true, false],
      ['AI-Powered Insights', true, false],
      ['Performance Reviews', true, false],
      ['Recruitment ATS', true, false],
      ['Onboarding Workflows', true, true],
      ['Mobile App', true, true],
      ['Biometric Attendance', true, false],
      ['Geo-fenced Clock-in', true, false],
      ['Custom Reporting', true, false],
      ['Time Tracking', true, true],
      ['Benefits Administration', true, true],
      ['Dedicated Support', true, false],
      ['Global Compliance', true, false],
      ['Leave Carry Forward', true, false],
    ],
    pricingUs: '$6 /employee /month',
    pricingThem: '$40 + $6/employee/month',
    verdict: 'Gusto is fine for basic US payroll, but HRMS Pro offers a complete HR platform — performance, recruiting, AI, and global support — at comparable pricing.'
  },

  rippling: {
    name: 'Rippling',
    slug: 'rippling',
    headline: 'HRMS Pro vs Rippling',
    title: 'HRMS Pro vs Rippling Comparison | Modern HR Without the Complexity',
    description: 'Compare HRMS Pro vs Rippling. See how HRMS Pro delivers enterprise HR features with simpler pricing and faster implementation.',
    subheadline: 'Rippling does everything — but at enterprise complexity and cost. HRMS Pro delivers the same power with a cleaner experience.',
    advantages: [
      { title: 'Simpler pricing', desc: 'All features included at $6/employee/month. No modules, no add-ons, no surprise fees.', icon: '💲' },
      { title: 'Faster implementation', desc: 'Average 6 weeks to go live vs Rippling\'s 3-6 month enterprise deployments.', icon: '⚡' },
      { title: 'Cleaner UX', desc: 'Designed for HR teams, not IT admins. Less complex, more intuitive.', icon: '✨' },
      { title: 'Dedicated support', desc: 'Every plan includes real human support with fast response times.', icon: '👩‍💻' },
      { title: 'AI-powered from day one', desc: 'AI insights, automation, and predictive analytics are built in — not bolted on as an upsell.', icon: '🚀' },
      { title: 'Dynamic configuration', desc: 'Adjust currency, tax rates, and attendance rules instantly. Changes propagate across the platform.', icon: '🔄' },
    ],
    features: [
      ['Core HR Database', true, true],
      ['Payroll Processing', true, true],
      ['Multi-Country Payroll', true, true],
      ['AI-Powered Insights', true, true],
      ['Performance Reviews', true, true],
      ['Recruitment ATS', true, true],
      ['Onboarding Workflows', true, true],
      ['Mobile App', true, true],
      ['Custom Reporting', true, true],
      ['Biometric Attendance', true, false],
      ['Geo-fencing', true, false],
      ['Device Management', false, true],
      ['App Management', false, true],
      ['Dedicated Support', true, true],
      ['Dynamic Settings', true, false],
    ],
    pricingUs: '$6 /employee /month',
    pricingThem: '$8+ /employee /month + module fees',
    verdict: 'Rippling is powerful but overkill for most companies. HRMS Pro delivers 90% of the functionality at half the complexity and lower cost.'
  }
};

export default comparisonData;
